version: '3.8'

services:

  marketplace-db-v2:
    image: mariadb:12
    container_name: marketplace-db-v2
    restart: always
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - db_data_v2:/var/lib/mysql
      - ./docker-init:/docker-entrypoint-initdb.d
    networks:
      - marketplace-network

  marketplace-auth-v2:
    build:
      context: .
      dockerfile: marketplace-auth-module/Dockerfile
    container_name: marketplace-auth-v2
    restart: on-failure
    env_file: .env
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      - marketplace-db-v2
      - marketplace-redis
    networks:
      - marketplace-network

  marketplace-backend-v2:
    build:
      context: .
      dockerfile: marketplace-backend-api/Dockerfile
    container_name: marketplace-backend-v2
    restart: on-failure
    env_file: .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - marketplace-db-v2
    networks:
      - marketplace-network

  marketplace-gateway-v2:
    build:
      context: .
      dockerfile: marketplace-gateway-api/Dockerfile
    container_name: marketplace-gateway-v2
    restart: on-failure
    env_file: .env
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - marketplace-auth-v2
      - marketplace-backend-v2
      - marketplace-redis
    networks:
      - marketplace-network

  marketplace-frontend-v2:
    build:
      context: .
      dockerfile: marketplace-frontend/Dockerfile
    container_name: marketplace-frontend-v2
    env_file: .env
    restart: on-failure
    ports:
      - "4207:80"
    depends_on:
      - marketplace-gateway-v2
    networks:
      - marketplace-network

  marketplace-redis:
    image: redis:alpine
    container_name: marketplace-redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - marketplace-network

networks:
  marketplace-network:
    driver: bridge

volumes:
  db_data_v2:
    driver: local