# Stage 1: Build
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration production

# Stage 2: Runtime con Nginx
FROM nginx:alpine
ARG APP_NAME=marketplace-frontend
COPY --from=build /app/dist/${APP_NAME} /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
