server.port=${PORT:8082}
jwt.secret=${JWT_SECRET}

# AUTH MODULE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# BACKEND API
spring.cloud.gateway.routes[1].id=api-service
spring.cloud.gateway.routes[1].uri=${API_SERVICE_URL}
spring.cloud.gateway.routes[1].predicates[0]=Path=/**